---
# If you cloned this repo from GitHub, don't change this file! If you update with a git pull, it's likely there will be
# changes that will need to be merged. If you're comfortable with this, that's fine, but ideally you should copy this
# and put your own data in that one. If you're missing data in your user-created config, Repost Bot will fall back on
# this file.
repost_data_path: "groups/"       # the folder where all group repost data will be stored.
bot_admin_id: 123                 # your personal user id, used to override group admin settings to reset group repost data.
                                  # use the /userid command in a private chat with the bot to echo your telegram user id.
bot_token: "2088043204:AAGtO_5P2AK6trkfszjW2Ar4PQGW2pv08yA"      # get this from BotFather
hash_size: 22                     # lower numbers = smaller file sizes, but less precise hashes and more false positives.
                                  # try not to go below 20; higher than 24 may result in false negatives.
repost_callout_timeout: 0        # time in seconds that must pass before repost bot will make another callout in a group.
auto_call_out: true               # whether the bot should automatically call out reposts or wait for a specific query.
callout_style: "verbose"         # "verbose" or "singular". determines if bot calls out each repost individually or
                                  # addresses it with a single response. warning: "verbose" can be very spammy, but it
                                  # is pretty funny.
                                  #
default_callouts:                 # repost bot can be configured by default to track URLs and pictures
  url: true                       # users can use the /toggle command to change these at any time
  picture: true

# these are the strings used for the bot's various responses, and also for its repost callout strategies.
# if you create a new strategy, the strings for its responses need to be in here and the keys to refer to it
# need to be returned in its get_required_strings() method
strings:
  private_chat: "I don't care about reposts just between us. I only check in group chats. Add me to a group."
  private_chat_toggle: "I don't track reposts in private chats."

  help_command: "I'm {name}. I analyze the pictures and URLs you send and call out reposts.\n
   I store the message id, and hashed versions of the URLs and pictures you send. GIFs and videos are not tracked.\n\n
   /toggle [url | picture] - Toggles whether I track URLs or pictures. You can toggle both at the same time with /toggle url picture. Reposts of untracked types will still be logged, but not called out.\n
   /settings - Display the current tracking settings.\n
   /whitelist - Use this command while replying to the message containing a specific URL or picture you want to whitelist. Whitelisted items will still be logged, but I won't call reposts of it out.\n
   /reset - Only group admins and the bot admin can call this command. Deletes all repost and whitelist data, resets tracking to defaults. This can't be undone.\n\n
   /stats - Display number of unique images and URLs I have seen, and how many reposts of each. Note that the first time it is seen is not counted as a repost.\n\n
   Flood protection is on a per-user-per-command basis, including calling out reposts. I will still track posts when being flooded, but will not call them out."

  invalid_whitelist_reply: "Use /whitelist while replying to a message so I can whitelist what's in it."
  removed_from_whitelist: "I'll start tracking reposts of that again."
  successful_whitelist_reply: "I won't track reposts of that from now on."

  group_repost_reset_initial_prompt: "Are you sure you want to delete the group's repost data? This is irreversible."
  group_repost_reset_admin_only: "Only admins can do this action."
  group_repost_reset_cancel: "I won't delete it then."
  group_repost_data_reset: "The group repost data has been reset."

  stats_command_reply: "Unique pictures posted: {num_unique_images:n}\nTotal image reposts: {num_image_reposts:n}\nUnique URLs posted: {num_unique_urls:n}\nTotal URL reposts: {num_url_reposts:n}"

  # these three strings are for the verbose callout response style
  repost_alert: [
      "Hey du Geringverdiener, das war ein REPOST!",
      "Wer seine Hausaufgaben nicht macht, fährt auch keinen Jetski! Nun mach deine Hausaufgaben und reposte weniger.",
      "Bist du gehirnkrank? Das war ein Repost!",
      "Reposts sind manchmal schon ein kleines Luxusproblem und das war einer.",
      "Lieber saudoof und reich, als ein Reposter zu sein.",
      "Ich bin die Stimme der Vernunft und du ein Geringverdiener. REPOST!",
      "REPOST! Ich buchstabiere es für dich - R-E-P-O-S-T.",
      "Konntest du dir keine weiteren Bilder leisten und machst deshalb einen Repost? Geringverdiener.",
      "Champagner macht keine Rotweinflecken, aber du einen Repost.",
      "Sogar aus Saint-Tropez sehe ich, dass das ein Repost war.",
      "Würdest du weniger reposten, hättest du auch einen Privatjet. REPOST!",
      "Ich wäre jetzt lieber auf Ibiza, statt dir zu sagen, dass das ein Repost war.",
      "Selbst Carmen sieht, dass das ein Repost war.",
      "Das ist zwar kein Bild meiner Carmen, aber es war ein Repost.",
      "Würde ich für jeden Repost 1 Euro bekommen, hätte ich schon längst meinen zweiten Privatjet.",
      "Soll ich dir meine Brille leihen, damit du auch siehst, dass das ein Repost war?",
      "Ich hätte mehr Geld verlangen sollen für diese Arbeit. Das war ein Repost!",
      "Ibiza, Saint-Tropez, Monaco und dann lande ich in dieser Gruppe und muss diesen Repost sehen.",
      "Ich sehe was, was du nicht siehst und das ist ein Repost.",
      "Carmen? Siehst du auch diesen Repost?",
      "Jetzt habe ich wegen deinem Repost meinen Champagner verschüttet.",
      "Wir haben ein Wort dafür, was du eben getan hast und das nennt sich Repost.",
      "Ich habe zwar nur einen Hauptschulabschluss, aber selbst ich sehe, dass das ein Repost war.",
      "Durch diesen Repost habe ich keine steuerlichen Vorteile. Weg damit.",
      "Die Carmen ertrage ich, aber diesen Repost nicht.",
      "Wer hat die Arbeit gemacht? Der Robert hat die Arbeit gemacht. REPOST!",
      "Bei dem Repost fliegen mir die Eier weg.",
      "Das habe ich schonmal gesehen. Weg damit.",
      "Diesen Geruch vom Repost rieche ich kilometerweit.",
      "Machst du noch einmal einen Repost, bekommst du einen Einlauf.",
      "Kennst du schon die Reaktionsemojis? Statt zu reposten, könntest du ja öfter diese Funktion nutzen! Win-Win.",
      "Ich habe Zeit für meine Carmen, aber nicht, um deine Reposts anzuschauen.",
      "Ich würde lieber mit meiner Carmen im neuen Privatjet düsen, statt mir deine Reposts anzuschauen.",
  ]
  
  first_repost_callout: "Hier wurde es bereits gepostet. Schau!"
  final_repost_callout: "Ich sehe alles, {name}."

  # one of these will be chosen at random for each message in a repost set, also part of the verbose style
  intermediary_callouts: [
      "Und hier auch!",
      "Auch hier!",
      "Hier noch eines!",
      "REPOST!",
      "Noch ein Repost!",
      "Und noch eines!",
      "Bist du blind?",
  ]

  # these next two string sets are for the single message callout style (singular)
  single_callout_one_repost_options: [
      "Hey {name} du Geringverdiener: Das war ein Repost. Zeigt mit dem Finger auf den Absender und lacht denjenigen aus."
  ]

  single_callout_x_num_reposts_options: [
      "{name}, das wurde bereits {num} Mal gepostet. Crazy oder?"
  ]
